# Generated by Django 5.2.13 on 2026-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category_task_completed_at_task_estimated_hours_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_user_id_c0fce1_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_due_dat_bce847_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_priorit_a900d4_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
