# Generated by Django 5.2.13 on 2026-04-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_category_alter_task_status_alter_task_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='secondary', max_length=20, verbose_name='Цвет'),
        ),
    ]
